# Generated by Django 5.2.7 on 2025-10-21 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositloanapplication',
            name='first_home_grant_approved',
            field=models.BooleanField(default=False, help_text='Has First Home Grant been approved?'),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='first_home_loan_approved',
            field=models.BooleanField(default=False, help_text='Has First Home Loan been approved?'),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='ird_number',
            field=models.CharField(blank=True, help_text='IRD number (8-9 digits, optional)', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IRD number (8-9 digits)', regex='^\\d{8,9}$')]),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='kiwisaver_withdrawal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='KiwiSaver withdrawal amount in NZD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='mortgage_pre_approval',
            field=models.BooleanField(default=False, help_text='Has mortgage pre-approval been obtained?'),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='mortgage_pre_approval_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-approved amount in NZD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='property_region',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], default='northland', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='region',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], default='northland', help_text='NZ region', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Is the business GST registered?'),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='ird_number',
            field=models.CharField(blank=True, help_text='IRD number (8-9 digits, optional)', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IRD number (8-9 digits)', regex='^\\d{8,9}$')]),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='nzbn',
            field=models.CharField(blank=True, help_text='New Zealand Business Number (13 digits, optional)', max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid NZBN (13 digits)', regex='^\\d{13}$')]),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='region',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], default='northland', help_text='NZ region', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='building_consent_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='building_consent_required',
            field=models.BooleanField(default=False, help_text='Does this renovation require a building consent?'),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='contractor_licensed',
            field=models.BooleanField(default=False, help_text='Is the contractor a Licensed Building Practitioner (LBP)?'),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='ird_number',
            field=models.CharField(blank=True, help_text='IRD number (8-9 digits, optional)', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IRD number (8-9 digits)', regex='^\\d{8,9}$')]),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='property_region',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], default='northland', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='region',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], default='northland', help_text='NZ region', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('id', 'Identification (Driver Licence/Passport)'), ('income', 'Income Proof (Payslips/Tax Returns)'), ('bank_statement', 'Bank Statement'), ('ird_summary', 'IRD Summary of Earnings'), ('quote', 'Contractor Quote'), ('valuation', 'Property Valuation'), ('building_consent', 'Building Consent'), ('kiwisaver', 'KiwiSaver Withdrawal Application'), ('first_home_grant', 'First Home Grant Approval'), ('mortgage_preapproval', 'Mortgage Pre-approval'), ('rates_notice', 'Rates Notice'), ('title', 'Property Title'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='Annual income in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='deposit_amount_required',
            field=models.DecimalField(decimal_places=2, help_text='Deposit amount in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('contractor', 'Contractor'), ('casual', 'Casual'), ('retired', 'Retired'), ('beneficiary', 'Beneficiary'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='existing_mortgage_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance in NZD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, help_text='Loan amount in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='other_deposit_sources',
            field=models.TextField(blank=True, help_text='Other sources: savings, family assistance, gifts, etc.'),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='phone_number',
            field=models.CharField(help_text='NZ phone number (e.g., 021234567 or +64212345678)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid NZ phone number (e.g., 021234567 or +64212345678)', regex='^(\\+64|0)[2-9]\\d{7,9}$')]),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='postcode',
            field=models.CharField(help_text='4-digit postcode', max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid 4-digit NZ postcode', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='property_postcode',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid 4-digit NZ postcode', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('unit', 'Unit'), ('townhouse', 'Townhouse'), ('lifestyle_block', 'Lifestyle Block'), ('section', 'Section/Land')], max_length=50),
        ),
        migrations.AlterField(
            model_name='depositloanapplication',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='Annual income in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='digital_marketing_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget in NZD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('contractor', 'Contractor'), ('casual', 'Casual'), ('retired', 'Retired'), ('beneficiary', 'Beneficiary'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, help_text='Loan amount in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='phone_number',
            field=models.CharField(help_text='NZ phone number (e.g., 021234567 or +64212345678)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid NZ phone number (e.g., 021234567 or +64212345678)', regex='^(\\+64|0)[2-9]\\d{7,9}$')]),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='postcode',
            field=models.CharField(help_text='4-digit postcode', max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid 4-digit NZ postcode', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='marketingloanapplication',
            name='traditional_marketing_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget in NZD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='Annual income in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('self_employed', 'Self Employed'), ('contractor', 'Contractor'), ('casual', 'Casual'), ('retired', 'Retired'), ('beneficiary', 'Beneficiary'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='estimated_property_value_after',
            field=models.DecimalField(decimal_places=2, help_text='Value in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='estimated_property_value_before',
            field=models.DecimalField(decimal_places=2, help_text='Value in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, help_text='Loan amount in NZD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='phone_number',
            field=models.CharField(help_text='NZ phone number (e.g., 021234567 or +64212345678)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid NZ phone number (e.g., 021234567 or +64212345678)', regex='^(\\+64|0)[2-9]\\d{7,9}$')]),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='postcode',
            field=models.CharField(help_text='4-digit postcode', max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid 4-digit NZ postcode', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='property_ownership',
            field=models.CharField(choices=[('owned', 'Owned (Freehold)'), ('mortgaged', 'Mortgaged')], max_length=50),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='property_postcode',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid 4-digit NZ postcode', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('unit', 'Unit'), ('townhouse', 'Townhouse'), ('lifestyle_block', 'Lifestyle Block'), ('commercial', 'Commercial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='renovationloanapplication',
            name='renovation_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('extension', 'Extension'), ('weathertightness', 'Weathertightness/Re-cladding'), ('insulation', 'Insulation'), ('earthquake_strengthening', 'Earthquake Strengthening'), ('full_renovation', 'Full Renovation'), ('other', 'Other')], max_length=50),
        ),
    ]
