# Generated by Django 5.2.7 on 2025-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_depositloanapplication_first_home_grant_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositloanapplication',
            name='customer_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='depositloanapplication',
            name='ird_number',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='customer_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='digital_marketing_budget',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='gst_registered',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='ird_number',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='nzbn',
        ),
        migrations.RemoveField(
            model_name='marketingloanapplication',
            name='traditional_marketing_budget',
        ),
        migrations.RemoveField(
            model_name='renovationloanapplication',
            name='customer_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='renovationloanapplication',
            name='ird_number',
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='_encrypted_customer_dob',
            field=models.BinaryField(blank=True, db_column='encrypted_customer_dob', null=True),
        ),
        migrations.AddField(
            model_name='depositloanapplication',
            name='_encrypted_ird_number',
            field=models.BinaryField(blank=True, db_column='encrypted_ird_number', null=True),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='_encrypted_customer_dob',
            field=models.BinaryField(blank=True, db_column='encrypted_customer_dob', null=True),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='_encrypted_ird_number',
            field=models.BinaryField(blank=True, db_column='encrypted_ird_number', null=True),
        ),
        migrations.AddField(
            model_name='marketingloanapplication',
            name='_encrypted_nzbn',
            field=models.BinaryField(blank=True, db_column='encrypted_nzbn', null=True),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='_encrypted_customer_dob',
            field=models.BinaryField(blank=True, db_column='encrypted_customer_dob', null=True),
        ),
        migrations.AddField(
            model_name='renovationloanapplication',
            name='_encrypted_ird_number',
            field=models.BinaryField(blank=True, db_column='encrypted_ird_number', null=True),
        ),
    ]
