# Generated by Django 5.2.7 on 2025-10-29 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_partner_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_email',
            field=models.EmailField(blank=True, help_text='General company email (may differ from primary contact)', max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='partner',
            name='hubspot_company_id',
            field=models.CharField(blank=True, help_text='HubSpot Company ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='hubspot_contact_id',
            field=models.CharField(blank=True, help_text='HubSpot Contact ID for primary contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_synced_to_hubspot',
            field=models.DateTimeField(blank=True, help_text='Last time this partner was synced to HubSpot', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='primary_contact_first_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='primary_contact_last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='primary_contact_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(help_text='Primary contact email - used as HubSpot contact identifier', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('family_office', 'Family Office'), ('mortgage_broker', 'Mortgage Broker')], max_length=50, verbose_name='Partner Type'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['email'], name='partners_pa_email_51fa03_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['hubspot_contact_id'], name='partners_pa_hubspot_cb319f_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['hubspot_company_id'], name='partners_pa_hubspot_b9490e_idx'),
        ),
    ]
