# Generated by Django 5.2.7 on 2025-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_company_email_partner_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='domain',
            field=models.URLField(blank=True, max_length=180, null=True),
        ),
    ]
