# Generated by Django 5.2.7 on 2025-10-26 19:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, help_text='Auto-generated from UUID', max_length=36, unique=True)),
                ('title', models.CharField(help_text='Notification headline', max_length=200)),
                ('html', models.TextField(help_text='HTML content (sanitized: p, a, strong, em, br only)')),
                ('notification_type', models.CharField(choices=[('account', 'Account'), ('marketing', 'Marketing'), ('feature', 'Feature/Function'), ('system', 'System'), ('application', 'Application'), ('security', 'Security')], db_index=True, default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen'), ('archived', 'Archived')], db_index=True, default='unseen', max_length=10)),
                ('action_url', models.CharField(blank=True, help_text='Optional URL for notification action', max_length=500)),
                ('action_text', models.CharField(blank=True, default='View', help_text='Text for action button', max_length=50)),
                ('seen_at', models.DateTimeField(blank=True, help_text='When notification was first seen', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('source', models.CharField(blank=True, help_text="System source (e.g., 'loan_application', 'user_registration')", max_length=100)),
                ('source_id', models.CharField(blank=True, help_text='Related object ID if applicable', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'status', '-created'], name='notificatio_user_id_d17531_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['-created'], name='notificatio_created_38238e_idx')],
            },
        ),
    ]
